baseURL = 'https://cyrus-studio.github.io/blog/'
languageCode = "zh-cn"
title = 'CYRUS STUDIO'
description = "¹«ÖÚºÅ£ºCYRUS STUDIO"
theme = "m10c"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "GitHub"
    url = "https://github.com/CYRUS-STUDIO"
    weight = 3
    pre = "<i class='fab fa-github'></i>"
    rel = "noopener noreferrer"
    target = "_blank"


[params.style]
  primaryColor = "#87CEFA"

[params]
  customCSS = ["css/custom.css"]
